modLoader = "javafml"
loaderVersion = "[47,)"
license = "check LICENSE.txt"

[[mods]]
modId = "zenadesidelight"
version = "1.20.1-0.1"
displayName = "Desi Delight"
authors = "ZENA [Naomi Miller]"
description = '''
Welcome to Desi Delight! An addon/expansion mod for Farmer's Delight.
'''

[[dependencies.zenadesidelight]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.zenadesidelight]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.zenadesidelight]]
    modId = "farmersdelight"
    mandatory = true
    versionRange = "[1.20.1-1.2.11,)"
    ordering = "AFTER"
    side = "BOTH"