modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="check LICENSE.txt"

[[mods]] #mandatory
modId="zenadesidelight" #mandatory
version="1.21.1-0.1" #mandatory
displayName="Desi Delight" #mandatory
authors= "ZENA [Naomi Miller]"
description='''
Welcome to Desi Delight! An addon/expansion mod for Farmer's Delight.
'''

[[dependencies.zenadesidelight]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.zenadesidelight]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.zenadesidelight]]
    modId = "farmersdelight"
    type = "required"
    versionRange = "[1.2.11,)"
    ordering = "AFTER"
    side = "BOTH"

